# naming the workflow
name: Events Demo 1
# mention the events to trigger
on: ...
# define jobs
jobs:
  # give the job name
  deploy:
    # on what os the vm should run
    runs-on: ubuntu-latest
    # define what happens under each steps
    steps:   
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."